"""Update3

Revision ID: 15f168be4a67
Revises: b2d6e59425c9
Create Date: 2026-03-05 17:44:25.524241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f168be4a67'
down_revision = 'b2d6e59425c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fulltime', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['member_id'])

    with op.batch_alter_table('p_subteam', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['p_subteam_id'])

    with op.batch_alter_table('parttime', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('rookie', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('scanning_log', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('veteran', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veteran', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('scanning_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('rookie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('parttime', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('p_subteam', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('fulltime', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
