"""Initial Migration

Revision ID: 7ea9d4af6bda
Revises: 
Create Date: 2026-03-04 19:26:28.539584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea9d4af6bda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=False))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_unique_constraint(None, ['member_id'])
        batch_op.drop_column('firstname')
        batch_op.drop_column('lastname')

    with op.batch_alter_table('p_subteam', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['p_subteam_id'])

    with op.batch_alter_table('s_subteam', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['s_subteam_id'])

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('s_subteam', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('p_subteam', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
