"""Migration Attempt

Revision ID: ae874ad3e353
Revises: fc8951b0c78b
Create Date: 2026-04-11 12:35:24.040328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae874ad3e353'
down_revision = 'fc8951b0c78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s_subteam')
    with op.batch_alter_table('fulltime', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'member', ['p_subteam_id'], ['member_id'])

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('parttime', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'member', ['p_subteam_id'], ['member_id'])

    with op.batch_alter_table('rookie', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'member', ['p_subteam_id'], ['member_id'])

    with op.batch_alter_table('scanning_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('event_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('check_in_date', sa.Date(), nullable=True))
        batch_op.create_foreign_key(None, 'member', ['member_id'], ['member_id'])
        batch_op.drop_column('p_subteam_id')

    with op.batch_alter_table('veteran', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'member', ['p_subteam_id'], ['member_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veteran', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('scanning_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_subteam_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('check_in_date')
        batch_op.drop_column('event_name')
        batch_op.drop_column('member_id')

    with op.batch_alter_table('rookie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('parttime', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('fulltime', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('s_subteam',
    sa.Column('s_subteam_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('s_subteam_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('s_subteam_id', name=op.f('s_subteam_pkey'))
    )
    # ### end Alembic commands ###
