"""Update

Revision ID: b2d6e59425c9
Revises: 7ea9d4af6bda
Create Date: 2026-03-05 14:10:30.788733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d6e59425c9'
down_revision = '7ea9d4af6bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_member')
    op.drop_table('s_subteam')
    with op.batch_alter_table('fulltime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_subteam_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fulltime_uuid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'member', ['p_subteam_id'], ['p_subteam_id'])
        batch_op.drop_column('uuid')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_subteam_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'p_subteam', ['p_subteam_id'], ['p_subteam_id'])

    with op.batch_alter_table('parttime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_subteam_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('parttime_uuid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'member', ['p_subteam_id'], ['p_subteam_id'])
        batch_op.drop_column('uuid')

    with op.batch_alter_table('rookie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_subteam_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('rookie_uuid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'member', ['p_subteam_id'], ['p_subteam_id'])
        batch_op.drop_column('uuid')

    with op.batch_alter_table('scanning_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_subteam_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('scanning_log_uuid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'member', ['p_subteam_id'], ['p_subteam_id'])
        batch_op.drop_column('uuid')

    with op.batch_alter_table('veteran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_subteam_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('veteran_uuid_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'member', ['p_subteam_id'], ['p_subteam_id'])
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veteran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('veteran_uuid_fkey'), 'team_member', ['uuid'], ['uuid'])
        batch_op.drop_column('p_subteam_id')

    with op.batch_alter_table('scanning_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('scanning_log_uuid_fkey'), 'team_member', ['uuid'], ['uuid'])
        batch_op.drop_column('p_subteam_id')

    with op.batch_alter_table('rookie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rookie_uuid_fkey'), 'team_member', ['uuid'], ['uuid'])
        batch_op.drop_column('p_subteam_id')

    with op.batch_alter_table('parttime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('parttime_uuid_fkey'), 'team_member', ['uuid'], ['uuid'])
        batch_op.drop_column('p_subteam_id')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('p_subteam_id')

    with op.batch_alter_table('fulltime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fulltime_uuid_fkey'), 'team_member', ['uuid'], ['uuid'])
        batch_op.drop_column('p_subteam_id')

    op.create_table('s_subteam',
    sa.Column('s_subteam_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('s_subteam_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('s_subteam_id', name=op.f('s_subteam_pkey')),
    sa.UniqueConstraint('s_subteam_id', name=op.f('s_subteam_s_subteam_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('team_member',
    sa.Column('uuid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('p_subteam_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('s_subteam_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], name=op.f('team_member_member_id_fkey')),
    sa.ForeignKeyConstraint(['p_subteam_id'], ['p_subteam.p_subteam_id'], name=op.f('team_member_p_subteam_id_fkey')),
    sa.ForeignKeyConstraint(['s_subteam_id'], ['s_subteam.s_subteam_id'], name=op.f('team_member_s_subteam_id_fkey')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('team_member_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('team_member_uuid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
