"""Migration Attempt

Revision ID: f58f55c99510
Revises: ae874ad3e353
Create Date: 2026-04-16 11:12:46.378782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58f55c99510'
down_revision = 'ae874ad3e353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s_subteam')
    with op.batch_alter_table('fulltime', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['member_id'])

    with op.batch_alter_table('p_subteam', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['p_subteam_id'])

    with op.batch_alter_table('parttime', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('rookie', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('scanning_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('check_in_date', sa.Date(), nullable=True))
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('veteran', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veteran', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('scanning_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('check_in_date')
        batch_op.drop_column('event_name')

    with op.batch_alter_table('rookie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('parttime', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('p_subteam', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('fulltime', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('s_subteam',
    sa.Column('s_subteam_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('s_subteam_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('s_subteam_id', name=op.f('s_subteam_pkey'))
    )
    # ### end Alembic commands ###
